version: "3.8"
services:
  db:
      image: mysql
      container_name: db_docker_kodistudio
      restart: always
      volumes:
          # to persist data into db-data directory project :
          - ./db-data:/var/lib/mysql
          # to persist data into db-data Docker volume
          # - db-data:/var/lib/mysql
      environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
          MYSQL_DATABASE: wordpress
      networks:
        - dev
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_docker_kodistudio
    restart: always
    depends_on:
        - db
    ports:
        - 8080:80
    environment:
        PMA_HOST: db
    networks:
        - dev
  maildev:
    image: maildev/maildev
    container_name: maildev_docker_kodistudio
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "8082:80"
    restart: always
    networks:
        - dev
        
  www:
    build: "php_7.4"
    container_name: www_docker_kodistudio
    ports:
      - "3000:80"
    volumes:
        - ./php_7.4/vhosts:/etc/apache2/sites-enabled
        - ./:/var/www
    restart: always
    networks:
        - dev

networks: 
  dev:

volumes:
  db-data:  

